Start-Process -FilePath "C:\Program Files\MongoDB\Server\4.0\bin\mongos.exe" -ArgumentList "--configdb config/localhost:27031,localhost:27032,localhost:27033 --port 27040"
Write-Host "Once all the shards are started, if this is the first launch, add the shards to the cluster by running the following commands on this mongos"
Write-Host "sh.addShard('store1/localhost:27050,localhost:27051,localhost:27052');"
Write-Host "sh.addShard('store2/localhost:27054,localhost:27053,localhost:27055');"
Write-Host "Then create the sharding tags, one for each store"
Write-Host "sh.addShardTag('store1','1')"
Write-Host "sh.addShardTag('store2','2')"
Write-Host "sh.addTagRange('store.sales',{'storeId':'1','deviceId':MinKey}, {'storeId':'1','deviceId':MaxKey},'1')"
Write-Host "sh.addTagRange('store.sales',{'storeId':'2','deviceId':MinKey}, {'storeId':'2','deviceId':MaxKey},'2')"
